### PR TITLE
Revert openblas

### PR DESCRIPTION
**Pull request by rodluger**
See https://github.com/rodluger/starry/issues/255

### CODE REVIEW

**Comment by fbartolic** [comment]
@rodluger  I'm getting the following error after this merge:
>WARNING (theano.tensor.blas): We did not find a dynamic library in the library_dir of the library we use for blas. If you use ATLAS, make sure to compile it with dynamics library.

This slows everything down by at least an order of magnitude.

I tried explicitly  pointing theano to the library by adding `export THEANO_FLAGS=blas.ldflags="-L/usr/lib/ -lopenblas"` to `azure-pipelines.yml` as suggested [here](https://stackoverflow.com/questions/6789368/how-to-make-sure-the-numpy-blas-libraries-are-available-as-dynamically-loadable) but it didn't work. Did you have this problem before?

**Comment by rodluger** [comment]
Looks like you were getting this warning before the merge as well:
https://dev.azure.com/constan7in3/volcano/_build/results?buildId=53&view=logs&j=d0f5d444-fce9-5962-ba7d-d71684238647&t=381d5e61-fc54-5591-7254-12d08113255d&l=18

Looking at my starry builds, it seems that I've always had this warning on Azure, but it's never noticeably impacted performance for me.

So, it doesn't seem like this is the issue causing the slowdown...

**Comment by fbartolic** [comment]
Hmmm,  there's definitely a noticeable slowdown compared to some previous builds. I might just give up on trying to build figures on azure again.

**Comment by dfm** [comment]
I don't understand why you're installing openblas anyways? MKL already implements everything you need and it should be better.

**Pull request merged**
